# Tensors

Create an Integer Tensor

In [1]:
import torch

t1 = torch.tensor(1.)
t1

tensor(1.)

In [2]:
t1.dtype

torch.float32

Create a Vector Tensor,

In [3]:
t2 = torch.tensor([1,2.,3,4])
t2

tensor([1., 2., 3., 4.])

Create a Matrix Tensor

In [4]:
t3 = torch.tensor([
    [1.,2,3],
    [4,5,6]
])
t3

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Create a 3D Array

In [5]:
t4 = torch.tensor([
    [
        [1,2,3.],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
t4

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

Print the created tensor and each shape

In [6]:
print(t1)
t1.shape

tensor(1.)


torch.Size([])

In [7]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [8]:
print(t3)
t3.shape

tensor([[1., 2., 3.],
        [4., 5., 6.]])


torch.Size([2, 3])

In [9]:
print(t4)
t4.shape

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])


torch.Size([2, 2, 3])

How about creating a tensor with different shape?

In [10]:
t5 = torch.tensor([
    [1,2.,3],
    [4,5],
    [6,7]
])

ValueError: expected sequence of length 3 at dim 1 (got 2)

### Tensor Operation and Gradients

In [11]:
x = torch.tensor(1.) # we do not need the gradient from the x (or usually called input)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)
x, w, b

(tensor(1.), tensor(2., requires_grad=True), tensor(3., requires_grad=True))

In [12]:
y = w * x + b
y

tensor(5., grad_fn=<AddBackward0>)

Compute the gradients of `y`

In [13]:
y.backward()
y

tensor(5., grad_fn=<AddBackward0>)

Now we display the gradients

In [14]:
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx None
dy/dw tensor(1.)
dy/db tensor(1.)


### Tensor Functions

Create a tensor with a fixed value for every element

In [15]:
# will create a matrix of 3 row and 2 columns with 42 as value
t6 = torch.full((2,3), 42)
t6

tensor([[42, 42, 42],
        [42, 42, 42]])

In [16]:
# concatenate two tensors
t7 = torch.cat((t3,t6))
t3, t6, t7

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[42, 42, 42],
         [42, 42, 42]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [42., 42., 42.],
         [42., 42., 42.]]))

In [17]:
# get the sin of the tensor
t8 = torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794],
        [-0.9165, -0.9165, -0.9165],
        [-0.9165, -0.9165, -0.9165]])

In [18]:
# reshape from 4 x 3 matrix to 3 dimensions 2 rows and 2 columns
t9 = t8.reshape(3,2,2)
t9

tensor([[[ 0.8415,  0.9093],
         [ 0.1411, -0.7568]],

        [[-0.9589, -0.2794],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

# Gradient Descent and Linear Regression