# Tensors

Create an Integer Tensor

In [1]:
import torch

t1 = torch.tensor(1.)
t1

tensor(1.)

In [2]:
t1.dtype

torch.float32

Create a Vector Tensor,

In [3]:
t2 = torch.tensor([1,2.,3,4])
t2

tensor([1., 2., 3., 4.])

Create a Matrix Tensor

In [4]:
t3 = torch.tensor([
    [1.,2,3],
    [4,5,6]
])
t3

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Create a 3D Array

In [5]:
t4 = torch.tensor([
    [
        [1,2,3.],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
t4

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

Print the created tensor and each shape

In [6]:
print(t1)
t1.shape

tensor(1.)


torch.Size([])

In [7]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [8]:
print(t3)
t3.shape

tensor([[1., 2., 3.],
        [4., 5., 6.]])


torch.Size([2, 3])

In [9]:
print(t4)
t4.shape

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])


torch.Size([2, 2, 3])

How about creating a tensor with different shape?

In [10]:
t5 = torch.tensor([
    [1,2.,3],
    [4,5],
    [6,7]
])

ValueError: expected sequence of length 3 at dim 1 (got 2)

### Tensor Operation and Gradients

In [11]:
x = torch.tensor(1.) # we do not need the gradient from the x (or usually called input)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)
x, w, b

(tensor(1.), tensor(2., requires_grad=True), tensor(3., requires_grad=True))

In [12]:
y = w * x + b
y

tensor(5., grad_fn=<AddBackward0>)

Compute the gradients of `y`

In [13]:
y.backward()
y

tensor(5., grad_fn=<AddBackward0>)

Now we display the gradients

In [14]:
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx None
dy/dw tensor(1.)
dy/db tensor(1.)


### Tensor Functions

Create a tensor with a fixed value for every element

In [15]:
# will create a matrix of 3 row and 2 columns with 42 as value
t6 = torch.full((2,3), 42)
t6

tensor([[42, 42, 42],
        [42, 42, 42]])

In [16]:
# concatenate two tensors
t7 = torch.cat((t3,t6))
t3, t6, t7

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[42, 42, 42],
         [42, 42, 42]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [42., 42., 42.],
         [42., 42., 42.]]))

In [17]:
# get the sin of the tensor
t8 = torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794],
        [-0.9165, -0.9165, -0.9165],
        [-0.9165, -0.9165, -0.9165]])

In [18]:
# reshape from 4 x 3 matrix to 3 dimensions 2 rows and 2 columns
t9 = t8.reshape(3,2,2)
t9

tensor([[[ 0.8415,  0.9093],
         [ 0.1411, -0.7568]],

        [[-0.9589, -0.2794],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

# Gradient Descent and Linear Regression

Create training data for temperature, rainfall, humidity. Our task is to predict the yield of apple and orange

In [19]:
import numpy as np

inputs = np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    [102,43,37],
    [69,96,70]
], dtype=np.float32)
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [20]:
# first column is for apple yield, second is for orange yield
targets = np.array([
    [56,70],
    [81,101],
    [119,133],
    [22,37],
    [103,119]
], dtype=np.float32)
targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

Convert to tensor

In [21]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
inputs, targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

### Create Linear Regression

In [22]:
# 2 row for apple and orange, 3 columns for features
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
w, b

(tensor([[ 2.1910, -0.3951, -0.0937],
         [ 0.8025, -0.4211,  0.1909]], requires_grad=True),
 tensor([ 0.6120, -0.6747], requires_grad=True))

In [23]:
def linear_regression(x):
    # @ is for matrix multiplication or we could use torch.matmul(x, w.t())
    return x @ w.t() + b

yhat = linear_regression(inputs)
yhat

tensor([[130.0470,  37.9054],
        [159.2179,  47.5169],
        [132.8403,  23.7897],
        [203.6304,  70.1406],
        [107.2934,  27.6375]], grad_fn=<AddBackward0>)

In [24]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

### Loss Function

In [29]:
def mean_squared_error(y_pred, y_true):
    diff = y_pred - y_true
    return torch.sum(diff ** 2) / diff.numel()

loss = mean_squared_error(yhat, targets)
loss

tensor(7006.3398, grad_fn=<DivBackward0>)

### Compute Gradients

In [30]:
loss.backward()

In [31]:
w, w.grad

(tensor([[ 2.1910, -0.3951, -0.0937],
         [ 0.8025, -0.4211,  0.1909]], requires_grad=True),
 tensor([[ 6509.9839,  4384.2407,  3202.7141],
         [-3926.9658, -5767.3555, -3261.2700]]))

In [32]:
b, b.grad

(tensor([ 0.6120, -0.6747], requires_grad=True), tensor([ 70.4058, -50.6020]))

### Adjust Weights and Biases to Reduce the Loss

In [33]:
# the use of torch.no_grad() is to indicate PyTorch that we shouldnt track, calculate, or modify gradients while updating the weights and biases
with torch.no_grad():
    w -= w.grad * 1e-5 # learning rate
    b -= b.grad * 1e-5

In [35]:
yhat = linear_regression(inputs)
yhat

tensor([[120.9794,  46.0391],
        [147.3852,  58.2535],
        [119.4435,  36.8265],
        [193.9193,  77.8332],
        [ 96.3500,  38.1672]], grad_fn=<AddBackward0>)

In [36]:
loss = mean_squared_error(yhat, targets)
loss

tensor(5808.2026, grad_fn=<DivBackward0>)

Before proceeding, reset gradients to zero. Because PyTorch accumulates gradient, otherwise when using the `backward()` function again, the new gradient values are added to existing gradients

In [37]:
w.grad.zero_()
b.grad.zero_()
w.grad, b.grad

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([0., 0.]))

### Train the Model with Gradient Descent